name: unleash
description: A Server Side Dart SDK for Unleash. Unleash is an open-source feature flag service.
version: 0.4.1
homepage: https://github.com/ivarconr/unleash-client-dart
repository: https://github.com/ivarconr/unleash-client-dart
issue_tracker: https://github.com/ivarconr/unleash-client-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.0
  yaml: ^3.0.0
  lints: ^1.0.0
