name: unleash
description: A dart client for Unleash. Unleash is a simple and easy to use feature toggle (feature flag) service.
version: 0.2.0
homepage: https://github.com/ueman/unleash
repository: https://github.com/ueman/unleash
issue_tracker: https://github.com/ueman/unleash/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.0
  test: ^1.16.0
  yaml: ^3.0.0
